{% set name = "dnspython" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dcfae8c7460a2f84b4072e26f1c9f4101ca20c071649cb7c34e8b6a93d58984

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - idna >=2.1
    - cryptography >=2.6

test:
  imports:
    - dns
    - dns.rdtypes
    - dns.rdtypes.ANY
    - dns.rdtypes.IN
    - dns.rdtypes.CH
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.dnspython.org
  summary: DNS toolkit
  description: |
    dnspython is a DNS toolkit for Python. It supports almost all record types.
    It can be used for queries, zone transfers, and dynamic updates. It supports
    TSIG authenticated messages and EDNS0.
  license: ISC
  license_file: LICENSE
  license_family: OTHER
  dev_url: https://github.com/rthalley/dnspython
  doc_url: https://dnspython.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
    - jan-janssen
